import type { AdSize, Config } from "./types";

const adDisplaySizes: AdSize[] = [
  { width: 300, height: 250 },
  { width: 336, height: 280 },
  { width: 728, height: 90 },
  { width: 300, height: 600 },
  { width: 320, height: 100 },
  { width: 468, height: 60 },
  { width: 234, height: 60 },
  { width: 120, height: 600 },
  { width: 160, height: 600 },
  { width: 970, height: 90 },
  { width: 970, height: 250 },
  { width: 250, height: 250 },
  { width: 200, height: 200 },
  { width: 320, height: 50 },
  { width: 300, height: 50 },
];

export const CONFIG: Config = {
  timestamp: new Date().toISOString(),
  debug: true,
  adSelectors: {
    adsense: [
      "ins.adsbygoogle[data-ad-client]",
      "ins.adsbygoogle[data-ad-slot]",
      'ins.adsbygoogle:not([data-adfriend-processed="true"])',
      'div[id^="google_ads_iframe"]',
      'iframe[id^="google_ads_iframe"]',
      "#google_ads_frame",
      ".adsbygoogle",
      ".google-ad-container",
      ".adsense-container",
      ".adsbygoogle-responsive",
    ],
    gam: [
      'div[id^="div-gpt-ad"]',
      'div[id^="gpt-ad"]',
      'div[id^="google_ads_iframe"]',
      ".dfp-ad",
      ".gpt-ad",
    ],
    meta: [
      'div[class*="fb_ad"]',
      'div[id^="fb-"]',
      ".fb-ad",
      'iframe[src*="facebook.com/plugins"]',
      'div[data-ad*="facebook"]',
    ],
    amazon: [
      'div[id^="amzn_assoc"]',
      'iframe[src*="amazon-adsystem.com"]',
      ".amzn_ads",
      'div[class*="amazon-ad"]',
    ],
    taboola: [
      "#taboola",
      '[id^="taboola"]',
      'div[id^="tbl-"]',
      ".trc_rbox_container",
      ".trc_related_container",
      'div[data-placement^="Below Article Thumbnails"]',
    ],
    outbrain: [
      'div[class*="OUTBRAIN"]',
      'div[id^="outbrain_widget"]',
      ".ob-widget",
      'div[data-widget-id^="AR_"]',
    ],
    medianet: [
      'div[id^="mdnativex"]',
      'div[id^="mdn-"]',
      'div[id^="_mN"]',
      ".medianet-ad",
    ],
    generic: [
      '.ad:not([data-adfriend-processed="true"])',
      '.ads:not([data-adfriend-processed="true"])',
      '.advertisement:not([data-adfriend-processed="true"])',
      '.advertising:not([data-adfriend-processed="true"])',
      '.ad-container:not([data-adfriend-processed="true"])',
      '.ad-wrapper:not([data-adfriend-processed="true"])',
      '.ad-unit:not([data-adfriend-processed="true"])',
      '.ad-zone:not([data-adfriend-processed="true"])',
      '.ad-space:not([data-adfriend-processed="true"])',
      '.rectangle-ad:not([data-adfriend-processed="true"])',
      '.leaderboard-ad:not([data-adfriend-processed="true"])',
      '.skyscraper-ad:not([data-adfriend-processed="true"])',
      '.banner-ad:not([data-adfriend-processed="true"])',
      '.sidebar-ad:not([data-adfriend-processed="true"])',
      '.header-ad:not([data-adfriend-processed="true"])',
      '.footer-ad:not([data-adfriend-processed="true"])',
      '.content-ad:not([data-adfriend-processed="true"])',
      'iframe[id*="ad-"]:not([data-adfriend-processed="true"])',
      'iframe[id*="-ad"]:not([data-adfriend-processed="true"])',
      'iframe[class*="ad-"]:not([data-adfriend-processed="true"])',
      'iframe[class*="-ad"]:not([data-adfriend-processed="true"])',
      '[class*="-ad-placement"]:not([data-adfriend-processed="true"])',
      '[class*="ad-placement"]:not([data-adfriend-processed="true"])',
      '[id*="ad-placement"]:not([data-adfriend-processed="true"])',
      '.sponsored-content:not([data-adfriend-processed="true"])',
      '.sponsored-post:not([data-adfriend-processed="true"])',
      '.sponsored:not([data-adfriend-processed="true"])',
      '.native-ad:not([data-adfriend-processed="true"])',
      '.promoted-content:not([data-adfriend-processed="true"])',
      '.recommended-content:not([data-adfriend-processed="true"])',
    ],
  },
  adSizes: {
    display: adDisplaySizes,
  },
};
