export default [
	{ text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
	{ text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
	{ text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
	{ text: "Believe in yourself and you're halfway there.", author: "Theodore Roosevelt" },
	{ text: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Dickens" },
	{ text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },
	{ text: "The greatest weapon against stress is our ability to choose one thought over another.", author: "William James" },
	{ text: "The only source of knowledge is experience.", author: "Albert Einstein" },
	{ text: "It is never too late to be what you might have been.", author: "George Eliot" },
	{ text: "The most important thing is to enjoy your life – to be happy – it's all that matters.", author: "Audrey Hepburn" },
	{ text: "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.", author: "Helen Keller" },
	{ text: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", author: "Buddha" },
	{ text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
	{ text: "The only thing we have to fear is fear itself.", author: "Franklin D. Roosevelt" },
	{ text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
	{ text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
	{ text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
	{ text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
	{ text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
	{ text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
	{ text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
	{ text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
	{ text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
	{ text: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson" },
	{ text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
	{ text: "The mind is everything. What you think you become.", author: "Buddha" },
	{ text: "Start anywhere.", author: "Derek Sivers" },
	{ text: "The only thing standing between you and your dream is the will to try and the belief that it is actually possible.", author: "Joel Brown" },
	{ text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
	{ text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
	{ text: "What lies behind you and what lies in front of you, pales in comparison to what lies inside of you.", author: "Ralph Waldo Emerson" },
	{ text: "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.", author: "Jimmy Dean" },
	{ text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
	{ text: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
	{ text: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain" },
	{ text: "If you want to live a happy life, tie it to a goal, not to people or things.", author: "Albert Einstein" },
	{ text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
	{ text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
	{ text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
	{ text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
	{ text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
	{ text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
	{ text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
	{ text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
	{ text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
	{ text: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson" },
	{ text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
	{ text: "The mind is everything. What you think you become.", author: "Buddha" },
	{ text: "Start anywhere.", author: "Derek Sivers" },
	{ text: "The only thing standing between you and your dream is the will to try and the belief that it is actually possible.", author: "Joel Brown" },
	{ text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
	{ text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
	{ text: "What lies behind you and what lies in front of you, pales in comparison to what lies inside of you.", author: "Ralph Waldo Emerson" },
	{ text: "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.", author: "Jimmy Dean" },
	{ text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
	{ text: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
	{ text: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain" },
	{ text: "If you want to live a happy life, tie it to a goal, not to people or things.", author: "Albert Einstein" },
	{ text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
	{ text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
	{ text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
	{ text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
	{ text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
	{ text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
	{ text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
	{ text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
	{ text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
	{ text: "The difference between ordinary and extraordinary is that little extra.", author: "Jimmy Johnson" } 
]
